server.port=8085

# Service URLs
client.service.url=http://localhost:8081
loan.service.url=http://localhost:8083
repayment.service.url=http://localhost:8084

# JWT Configuration - Resource Server
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/oauth2/jwks

# JWT Secret (pour compatibilité)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/microfinance_reporting
spring.datasource.username=postgres
spring.datasource.password=okomothom-96
spring.datasource.driver-class-name=org.postgresql.Driver

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Logging
logging.level.com.microfinancehub.micorhub_reporting_service=DEBUG
logging.level.org.springframework.security=DEBUG