server.port=8084

# Service URLs
client.service.url=http://localhost:8081
loan.service.url=http://localhost:8083
repayment.service.url=http://localhost:8084

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Database - CORRIGÉ : microfinance_repayment
spring.datasource.url=jdbc:postgresql://localhost:5432/microfinance_repayment
spring.datasource.username=postgres
spring.datasource.password=okomothom-96
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - Laissez Hibernate créer les tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Désactiver Flyway complètement
spring.flyway.enabled=false

# Logging
logging.level.com.microfinancehub.micorhub_repayment_service=DEBUG